version: '3'

include:
  - ros-foxglove-bridge/docker-compose.yml
  - ros-rosbridge-suite/docker-compose.yml
  - ros-helix/docker-compose.yml
  # - ros-helix-proprietary/docker-compose.yml

services:
  nginx:
    image: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ros-helix/helix_description/meshes:/usr/share/nginx/html/meshes
    network_mode: "host"
    restart: always

  studio:
    image: ghcr.io/helix-robotics-ag/studio:latest
    build:
      context: studio
      dockerfile: Dockerfile
    volumes:
      - ./config/studio/helix_interface_layout.json:/foxglove/default-layout.json
    ports:
      - 8080:8080
    restart: always
